### ISSUE TITLE
Auto-detected mode as 'legacy' nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: 

### ISSUE THREAD

**Issue by ianuragbhatt** [Atinoda/text-generation-webui-docker#20] opened 2023-08-08 15:47 UTC
I am getting this error when composing my GPU is RTX 3070TI
Cannot start Docker Compose application. Reason: compose [start] exit status 1. Container text-generation-webui-text-generation-webui-1 Starting Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy' nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown

**Comment by Atinoda** [comment] 2023-08-08 17:08
I had had the `failed to create shim task: OCI runtime create failed` error before. Unfortunately, I was only able to solve it by reinstalling docker. In my case, that error was intermittently thrown every time I tried to start any container.

Could you please try to run a different docker image that uses GPU and see if there is still an error? You can try my [cuda_memtest-docker](https://github.com/Atinoda/cuda_memtest-docker) repository, or anything else that you like.

**Comment by ianuragbhatt** [comment] 2023-08-08 17:38
I got same error should I reinstall docker. 
GPU : RTX 3070ti
CUDA version: 12.2
Driver Version: 535.86.10

**Comment by Atinoda** [comment] 2023-08-08 17:52
Yes, I think it is easiest to try and reinstall docker. Try to google for `OCI runtime create failed` plus some more specific queries about your system - you may find other people have similar problems. I did not have the patience for troubleshooting it (nor could I find a satisfactory root cause) so I just went for full re-installation.

I'm going to close this issue because it is not related to the docker image of the project. Please feel welcome to get in touch if you have any issues with this container, once you get Docker up and running :)

**Closed by Atinoda** 2023-08-08 17:52 UTC
Labels: unrelated
